FROM postgres:17.6

ENV POSTGRES_USER=user \
    POSTGRES_PASSWORD=password \
    POSTGRES_DB=postgres_db

COPY sql/01_init.sql /docker-entrypoint-initdb.d/01_init.sql
COPY sql/02_seed.sql /docker-entrypoint-initdb.d/02_seed.sql

CMD [ \
  "postgres", \
  "-c", "maintenance_work_mem=1GB", \
  "-c", "track_io_timing=on",  \
  "-c", "shared_preload_libraries=pg_stat_statements"  \
]